interface CardsContent {
  id: string | number | bigint;
  imageLink: string;
  imageSrc: string;
  captionLink: string;
  caption: string;
  projectKind: string;
}

export const galleryCards: CardsContent[] = [{
  id: "gi-1",
  imageLink: "",
  imageSrc: "/woods-image.jpg",
  captionLink: "",
  caption: "Woods",
  projectKind: "Photography",
}, {
  id: "gi-2",
  imageLink: "",
  imageSrc: "/path-image.jpg",
  captionLink: "",
  caption: "Path",
  projectKind: "Website",
}, {
  id: "gi-3",
  imageLink: "",
  imageSrc: "/darkness-image.jpg",
  captionLink: "",
  caption: "Darkness",
  projectKind: "Website",
}, {
  id: "gi-4",
  imageLink: "",
  imageSrc: "/waves-image.jpg",
  captionLink: "",
  caption: "Waves",
  projectKind: "Photography",
}, {
  id: "gi-5", 
  imageLink: "",
  imageSrc: "/drops-image.jpg",
  captionLink: "",
  caption: "Drops",
  projectKind: "Website",
}, {
  id: "gi-6",
  imageLink: "",
  imageSrc: "/ocean-image.jpg",
  captionLink: "",
  caption: "Ocean",
  projectKind: "Website",
}, {
  id: "gi-7",
  imageLink: "",
  imageSrc: "/town-image.jpg",
  captionLink: "",
  caption: "Town",
  projectKind: "Website",
}, {
  id: "gi-8",
  imageLink: "",
  imageSrc: "/mountain-image.jpg",
  captionLink: "",
  caption: "Mountain",
  projectKind: "Photography",
}, {
  id: "gi-9", 
  imageLink: "",
  imageSrc: "/camera-image.jpg",
  captionLink: "",
  caption: "Camera",
  projectKind: "Website",
}];